services:
  agente-ia:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
